---
# tasks file for ansible_role_tigervnc

- name: Install tigervnc package
  kewlfft.aur.aur:
    name: tigervnc
    state: present

- name: Create config dir
  file:
    state: directory
    path: '{{tigervnc_config_path | dirname}}'

- name: Create config
  copy:
    dest: '{{tigervnc_config_path}}'
    content: >-
      session={{tigervnc_session}}
      geometry={{tigervnc_geometry}}
      alwaysshared
      {{ 'localhost' if not tigervnc_expose_to_network }}

- name: Create passwd file
  shell:
    cmd: 'printf {{tigervnc_passwd}} | vncpasswd > {{tigervnc_config_path}}/passwd'

- name: 'Copy :: systemd service'
  template:
    src: '{{role_path}}/files/x0vncserver.service'
    dest: '/etc/systemd/system/x0vncserver.service'
    owner: root
    group: root
  notify: daemon-reload
  become: true

- name: 'Enable systemd service'
  systemd:
    name: x0vncserver.service
    state: restarted
    enabled: true
  when: tigervnc_daemon_enable
